Primer prueba de changes
MarkArthur2211/Retos pull request #1
Opened 2022-11-29 00:11 UTC by MarkArthur2211

Agregue un hola, por que edwin me dijo

2022-11-29 00:14 UTC, edlingao commented on index.html
> +                        <p>hola</p>
Quita eso

2022-11-29 02:09 UTC, edlingao requested changes

2022-11-29 02:09 UTC, edlingao commented on HOLAMUNDO.html
> +        </main>
Cambia esta etiqueta main por una etiqueta `<header>`

2022-11-29 02:09 UTC, edlingao commented on HOLAMUNDO.html
> +        </header>
Esta seccion debe ser una etiqueta `<main>`

2022-11-29 02:09 UTC, edlingao commented on HOLAMUNDO.html
> +        </main>
Esto debe ser un `<aside>` ya que estara a un lado de la pagina

2022-11-29 02:09 UTC, edlingao commented on HOLAMUNDO.html
> +        </div>
estas 3 secciones deben ser `<div>` y todas deben ir metidas dentro de una etiqueta `<footer>` y elimina la etiqueta `<header>`
Ejemplo:
```
<footer>
  <div></div>
  <div></div>
  <div></div>
</footer>
```

2022-11-29 02:09 UTC, edlingao commented on HOLAMUNDO.html
> +        <!--ya hice el cambio del main ogt xd-->
❤️

2022-11-29 02:22 UTC, MarkArthur2211 commented on HOLAMUNDO.html
> +        </div>
listo,

2022-11-29 02:24 UTC, MarkArthur2211 commented on HOLAMUNDO.html
> +        </main>
aqui tengo unda duda:
dejo el main y pongo el <asaide>? 
<main>
   <asaide>
<articule>....?

_y borro el <section>?_

2022-11-29 02:30 UTC, edlingao commented on HOLAMUNDO.html
> +        </main>
El section sobra, borra el `<section>` y cambiale el nombre al `<main>` por `<aside>` 

Ejemplo
```
<aside>

     <div>
          <h1><samp style="color:darkgoldenrod"> NEW</samp> </h1>
      </div>
      <div>
          <h5> Hydrogen VS Electric cars</h5>
          <p> will hrydogen- fueld cars ever catch up to EVs? </p>
      </div>

</aside>

```

2022-11-29 02:31 UTC, edlingao commented on HOLAMUNDO.html
> +        </div>
Dale "Resolve" cuando ya esten pls

2022-11-29 02:44 UTC, edlingao requested changes

2022-11-29 02:44 UTC, edlingao commented on HOLAMUNDO.html
> +                <h1 id="titulo"> W.</h1>
Cambia el `<h1>` por `<img>` con el logo en la carpeta de imagenes

2022-11-29 02:46 UTC, MarkArthur2211 commented on HOLAMUNDO.html
> +                <h1 id="titulo"> W.</h1>
No hay fotos con la letra W

2022-11-29 02:57 UTC, merged

2022-11-30 18:12 UTC, MarkArthur2211 commented
Sobres nalgon, ponme mas cosas para hacer...
¿Empiezo con el css? @edlingao